import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Carrusel from '../components/Carrusel';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import Footer from '../components/Footer';
import FloatingButton from '../components/FloatingButton';
import Portfolio from '../components/Portfolio'; // Asegúrate de importar el componente Portfolio


export default function Home() {
  const [zoomedImage, setZoomedImage] = useState(null);
  const [imageData, setImageData] = useState([]); // Agregado
  useEffect(() => {
    fetch('/api/image/imageFiles')
      .then((response) => response.json())
      .then((data) => {
        const newImageData = data.imageFiles.map((fileName, index) => {
          const imagePath = `/imagenes_proyecto/${fileName}`;
          const altText = fileName.replace(/\.[^/.]+$/, '');
          const stories = [
            "Historia de la imagen 1.",
            "Historia de la imagen 2.",
            "Historia de la imagen 3.",
            // Agrega más historias para cada imagen
          ];
          return {
            src: imagePath,
            alt: altText,
            story: stories[index],
          };
        });
        setImageData(newImageData);
      })
      .catch((error) => console.error('Error al obtener archivos de imagen:', error));
  }, []);


  return (
    <div>
      <Head>
        <title>VIDRIERIA</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Carrusel heading='Captur Photography' message='I capture moments in nature and keep them alive.' />
      <Slider slides={SliderData} />
      <Instagram />
      <FloatingButton />
      <Portfolio imageData={imageData} setZoomedImage={setZoomedImage} />
      {/* Imagen Ampliada */}
      {zoomedImage !== null && (
        <div className='image-zoom-container'>
          <img src={imageData[zoomedImage].src} alt='Zoomed Image' />
          {/* Agrega botones para navegar entre imágenes ampliadas */}
          <button onClick={() => setZoomedImage(null)}>Cerrar</button>
        </div>
      )}
      <Footer />
    </div>
  );
}
